"""empty message

Revision ID: c13d14623efb
Revises: b8757cb49af5
Create Date: 2019-07-20 21:31:36.930937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13d14623efb'
down_revision = 'b8757cb49af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'type')
    # ### end Alembic commands ###
